# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.2)
neo_version=21.1.200
neo_version_range=[21.1.197,)
loader_version_range=[4,)
jei_version=19.16.4.166
curios_version=9.5.1+1.21.1

## Mod Properties
mod_id=theaurorian
mod_name=The Aurorian
mod_license=GNU LESSER GENERAL PUBLIC LICENSE Version 2.1
mod_version=1.0.0
mod_group_id=cn.teampancake.theaurorian
mod_authors=Team Pancake
mod_description=