modLoader="javafml"
loaderVersion="[47,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]]
modId="theaurorian"
version="${mod_version}"
displayName="The Aurorian"
logoFile="the_aurorian_logo.png"
authors="Team Pancake"
description='''${mod_description}'''

[[dependencies.theaurorian]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.theaurorian]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.theaurorian]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.2.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.theaurorian]]
    modId="pancake_lib"
    mandatory=true
    versionRange="[0.0.1,)"
    ordering="NONE"
    side="BOTH"

#openGLVersion="[3.2,)"
