modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]]
modId="theaurorian"
version="${mod_version}"
displayName="The Aurorian"

authors="Team Pancake"

description='''${mod_description}'''

[[dependencies.theaurorian]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.theaurorian]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

#openGLVersion="[3.2,)"
